name: checklist_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.5+8

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^7.2.0
  google_fonts: ^6.1.0
  go_router: ^13.0.1
  hive_flutter: ^1.1.0
  iconsax: ^0.0.8
  overlay_support: ^2.0.1
  provider: ^6.0.3
  uuid: ^4.3.3
  flex_color_scheme: ^7.3.1
  flutter_screenutil: ^5.9.0

dev_dependencies:
  device_preview: ^1.1.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_native_splash: ^2.3.9
  flutter_lints: ^3.0.1
  mocktail: ^1.0.2

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash.png
    color: "#FFFFFF"