name: Deploy

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Get Flutter Version
      run: |
        versionName=`cat pubspec.yaml | grep -o 'version:[^:]*' | cut -f2 -d":" | xargs`
        echo "VERSION_NAME=$versionName" >> $GITHUB_ENV

    - name: Create Tag and Release
      uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ env.VERSION_NAME }}
          automatic_release_tag: ${{ env.VERSION_NAME }}
          draft: false
          prerelease: false
